setup project
masangana/math-magicians pull request #1
Opened 2022-06-27 22:25 UTC by masangana

- Setup the files for my futur project

2022-06-27 23:51 UTC, MahmoudBakr23 requested changes
Hello @masangana 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are so[template ](https://github.com/microverseinc/readme-template) me excel[template](https://github.com/microverseinc/readme-template) lent points that you have made perfectly. Keep up! 💪
- Well done installing the correct packages for react
- Correct Linters
- Descriptive PR 

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-27 23:51 UTC, MahmoudBakr23 commented on README.md
> +# Getting Started with Create React App
Kindly make sure to update the README file with more descriptive and project-related details.
You can use this [template](https://github.com/microverseinc/readme-template) from Microverse

2022-06-28 08:11 UTC, BenMukebo approved these changes
### Hi @masangana, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 08:11 UTC, BenMukebo commented on .eslintrc.json
> +    "jest": true
- [OPTIONAL] -Great job on adding the linters 👏 . but you have a problem with your linter configuration because it doesn't run, please let's follow [these instructions](https://github.com/microverseinc/linters-config/tree/master/react-redux) on how to setup the linters correctly. 💯 👍🏻

2022-06-28 23:58 UTC, closed without merging